### PR TITLE
agrego mi info

### PR DESCRIPTION
**Pull request by cantor11**

### CODE REVIEW

**Review by oscar-230 — APPROVED** [review]
Bien

**Review by nheredia11 — APPROVED** [review]
Good Commit

**Review by kevinJ1910 — APPROVED** [review]
Bien para mi

**Review by GUERRERO13055030 — APPROVED** [review]

**Review by oscar-230 — APPROVED** [review]
Good

**Review by Hazzard1912 — APPROVED** [review]
Good enough

**Review by XxCr1ss — APPROVED** [review]
Nice

**Pull request merged**
