### PR TITLE
feat: Agrego informacion personal a info.json

### PR DESCRIPTION
**Pull request by Hazzard1912**

### CODE REVIEW

**Review by XxCr1ss — APPROVED** [review]
👍🏽

**Review by nheredia11 — APPROVED** [review]
Good 💻👍

**Review by oscar-230 — APPROVED** [review]
Good

**Review by kevinJ1910 — APPROVED** [review]
Todo bien

**Review by XxCr1ss — APPROVED** [review]
👍🏽

**Review by cantor11 — APPROVED** [review]
good

**Review by GUERRERO13055030 — APPROVED** [review]

**Pull request merged**
